In [1]:
import numpy as np

Frequently in Numpy, a matrix or vector computation can be done in multiple ways.  
Sometimes they have a meaningful difference in computational efficiency.  
Therefore, when you are iteratively computing large arrays, it can be helpful to check their relative efficiency with toy arrays.

# Vector & Matrix

In [33]:
# 1 dimensional array can be interpreted as both a column and row vector as required.
a = np.array([1,2,3,4])
print(a.shape)

(4,)


In [36]:
# explicit row vector
a = np.array([[1,2,3]])
print(a.shape)
print(a)

(1, 3)
[[1 2 3]]


In [37]:
# explicit column vector
a = np.array([[1,2,3]]).T
print(a.shape)
print(a)

(3, 1)
[[1]
 [2]
 [3]]


In [39]:
# two dimensional matrix
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
# above matrix can be more conveniently created
a = np.arange(1, 10, 1).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Product

In [50]:
# inner product or dot product
# inner product can be calculated in multiple ways
a = np.array([[1,2,3]])
b = np.array([[1,2,3]]).T

c = a@b
d = np.dot(a,b)
e = np.matmul(a,b)

print(c, d, e)

[[14]] [[14]] [[14]]


In [51]:
# @ operator and matmul function are computationally more efficient
%timeit a@b
%timeit np.dot(a,b)
%timeit np.matmul(a,b)

1.08 µs ± 23.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.55 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.09 µs ± 42.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [63]:
# outer product
# outer product can be computed with broadcasting or a designated function
print(a*b)
print(np.multiply(a,b))
print(np.outer(a,b))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [66]:
# The Python built-in operator multiply function are much more efficient than outer function
%timeit a*b
%timeit np.multiply(a,b)
%timeit np.outer(a,b)

1.38 µs ± 139 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.38 µs ± 52.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
4.25 µs ± 303 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [70]:
# matrix multiplication
a = np.arange(1, 21).reshape(5,4)
b = np.arange(1,9).reshape(4,2)

In [71]:
print(a@b)
print(np.matmul(a,b))

[[ 50  60]
 [114 140]
 [178 220]
 [242 300]
 [306 380]]
[[ 50  60]
 [114 140]
 [178 220]
 [242 300]
 [306 380]]


In [73]:
# both methods are computationally equivalent
%timeit a@b
%timeit np.matmul(a,b)

1.15 µs ± 51.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.17 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Trace

- The trace of a square matrix A, denoted tr(A),is defined to be the sum of elements on the main diagonal (from the upper left to the lower right) of A.
- The trace of a matrix is the sum of its (complex) eigenvalues (counted with multiplicities), and it is invariant with respect to a change of basis. This characterization can be used to define the trace of a linear  operator in general. 
- The trace is only defined for a square matrix (n × n).



In [80]:
print('Diagonal matrix')
print(a)
print('tr(a) = ',np.trace(a))

Diagonal matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
tr(a) =  34


In [81]:
# for non-diagonal matrix, the matrix truncated to a square matrix for trace calculation
print('Non-diagonal matrix')
print(b)
print('tr(b) = ',np.trace(b))

Non-diagonal matrix
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
tr(b) =  5


# Norm

A norm of a vector $\parallel x \parallel$ is informally a measure of the “length” of the vector.  

$l2$ and $l1$ norm are commonly used.  
$l2$ norm,
$$
{\parallel x \parallel}_2 = \sqrt{\sum_{i=1}^{n} {x_i}^2}
$$
$l1$ norm,
$$
{\parallel x \parallel}_1 = {\sum_{i=1}^{n} {\mid x_i \mid}}
$$

More generally, $l2$ and $l1$ norm belong to the family of $l_p$ norms.
$$
{\parallel x \parallel}_p = \left( {\sum_{i=1}^{n} {\mid x_i \mid}}^p \right) ^{1/p}
$$

In [99]:
a = np.arange(1, 10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
# l1 & l2 norm
l2 = np.linalg.norm(a, ord = 2)
l1 = np.linalg.norm(a, ord = 1)
print('l2 norm', l2)
print('l1 norm', l1)

l2 norm 16.84810335261421
l1 norm 18.0


# Matrix rank

A set of vectors ${x1, x2, . . . xn} \in R$ is said to be **linearly independent** if no vector can be represented as a linear combination of the remaining vectors. Conversely, if one vector belonging to the set can be represented as a linear combination of the remaining vectors, then the vectors are said to be linearly dependent.  
If 
$$
x_n = \sum_{i=1}^{n-1} \alpha_i x_i
$$
for some scalar values $\alpha_1, . . . , \alpha_{n−1} \in R$, then we say that the vectors $x_1, . . . , x_n$ are linearly dependent; otherwise, the vectors are linearly independent.

For a matrix, column rank is equal to row rank and both are simply referred as the rank of a matrix.

In [102]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

For the above, matrix, 
$$
(2*\text{row}_2) - \text{row}_1 = \text{row}_3
$$
Therefore, the rank of a is 2.

In [105]:
print('rank of a: ',np.linalg.matrix_rank(a))

rank of a:  2


# Inverse matrix

The inverse of a square matrix $A ∈ R^{n×n}$ is denoted $A^{-1}$, and is the unique matrix such that
$$
A^{-1}A = AA^{-1} = I
$$

Note that not all matrices have inverses. Non-square matrices, for example, do not have inverses by definition.  
However, for some square matrices A, it may still be the case that $A^{−1}$ may not exist. In particular, we say that A is invertible or non-singular if $A^{−1}$ exists and non-invertible or singular otherwise.  
In order for a square matrix A to have an inverse, then A must be full rank, meaning the rank of a matrix is equal to the size of the matrix.

Properties of inverse matrix include:
$$
\begin{aligned}
& (A^{−1})^{−1} = A \\
& (AB)^{−1} = B^{−1}A^{−1} \\
& (A^{−1})^{T} = (A^{T})^{−1}
\end{aligned}
$$

As an example of how the inverse is used, consider the linear system of equations, 
$$
Ax = b\\ \text{ where } A ∈ R^{n×n},\\ \text{and } x, b ∈ R^{n}
$$
If A is nonsingular (i.e., invertible), then 
$$
x = A^{-1}b.
$$

In [114]:
# inverse matrix calculation when the matrix is invertible
a = np.array([[1,2],
              [3,4]])
print('inverse: \n', np.linalg.inv(a))

inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


The Moore-Penrose pseudo-inverse is a generalization of the matrix inverse when the matrix may not be invertible. If A is invertible, then the Moore-Penrose pseudo inverse is equal to the matrix inverse. However, the Moore-Penrose pseudo inverse is defined even when A is not invertible.  
More formally, the Moore-Penrose pseudo inverse, $A^+$, satisfies the following four criteria when $A \in R^{mxn}$.
$$
AA^{+}A = A  \\
A^{+}AA^{+} = A^{+} \\
(AA^{+})^{T} = AA^{+} \\
(A^{+}A)^{T} = A^{+}A
$$
When A is a full rank matrix (invertible matrix) and if m>n, then $A^{+} = A^{-1}$.  
Otherwise, $x = A^{+}b$ is not the exact solution for $Ax = b$.  
It finds the solution that is closest in the least squares sense.

In [118]:
# as we've seen before, a is not a full-rank matrix and the inverse does not exist
# the error message states 'singular matrix' which indicates non-invertible matrix
a = np.arange(1, 10).reshape(3,3)
print(a)
np.linalg.inv(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


LinAlgError: Singular matrix

In [117]:
#Moore-Penrose pseudo-inverse calculation
print('pseudo inverse: \n', np.linalg.pinv(a))

pseudo inverse: 
 [[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  3.78742005e-17  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]


# Orthogonal Matrix

##### Orthogonal vectors

Two vectors $x, y ∈ R^n$ are orthogonal if 
$$
x^{T}y = 0
$$

In [132]:
# x and y are both column vectors by conventional notation where the default numpy array is a row vector.
# there is an extra transpose to denote column vector in numpy expression
x_t = (np.array([[0,1,0,1]]).T).T
y = np.array([[1,0,1,0]]).T
print(x_t@y)
print('vector x and y are orthogonal')

[[0]]
vector x and y are orthogonal


##### Orthogonal matrices

- A vector $x ∈ R^n$ is normalized if ${\parallel x \parallel}_2 = 1$.
- A square matrix $U ∈ R^{n×n}$ is orthogonal if all its columns are orthogonal to each other and are normalized (the columns are then referred to as being orthonormal).

An orthogonal matrix follows
$$
U^{T}U = UU^{T} = I
$$
In other words, transpose of an orthogonal matrix is its inverse.

In [144]:
a = np.array([[1,0,0],
              [0,0,1],
              [0,1,0]])
print(np.array_equal((a.T @ a), np.eye(3)))
print(np.array_equal((a @ a.T), np.eye(3)))

True
True


In [148]:
print('Is transpose equal to inverse?')
print(np.array_equal(a.T, np.linalg.inv(a).astype(int)))

Is transpose equal to inverse?
True
